### ISSUE TITLE
RangeError: Invalid count value

### ISSUE THREAD

**Issue by eight04** [indentjs/endent#1]
`endent` throws with the following code:
```js
var endent = require("endent")
const a = '"test"';
console.log(endent`
    {
        ${a}: null
    }
`);
```
https://runkit.com/embed/dc58pgajgtpl

The line throwing the error:
https://github.com/indentjs/endent/blob/2ffcf9a88dcf03a4ef91aa7e83e90f8d02ae6c46/endent.js#L29

**Comment by ZhouHansen** [comment]
nice catch! fixed: 
https://runkit.com/zhouhansen/5b39848c12e4e600121297b7
