### ISSUE TITLE
The compiled output is using import syntax

### ISSUE THREAD

**Issue by thetutlage** [indentjs/endent#7]
The compiled Javascript output must use require and not import, since the import is not yet supported in Node.js properly.

This is happening, coz you are using `esnext` for the module property inside the `tsconfig.json` file.

Mind fixing it and push a new release?

**Comment by zhouhancheng** [comment]
Thanks 2.0.1 🎉

**Comment by zhouhancheng** [comment]
@thetutlage By the way, I lost my phone to do [github 2 factor authentication](https://help.github.com/en/github/authenticating-to-github/recovering-your-account-if-you-lose-your-2fa-credentials), and I lost my recovery code, so I can't regain my account: https://github.com/ZhouHansen, I used it for 6 years, I don't want to lose it. Do you know someone work at Github? If you do, May I ask you to help me to regain my account?

**Comment by thetutlage** [comment]
Nope, no connections with anyone at github. But this article may help you, there is a section describing steps to re-again access with email verification https://help.github.com/en/github/authenticating-to-github/recovering-your-account-if-you-lose-your-2fa-credentials#authenticating-with-a-verified-device-ssh-token-or-personal-access-token

**Comment by hanszhoou** [comment]
@thetutlage could you please close this issue, since I lost my 2 factor authentic token, this project has moved to https://github.com/zhouhanseng/endent thanks!
